
name = "YomuraDashComponents"
uuid = "1b08a953-4be3-4667-9a23-441f5db0cfd8"
authors = ["yomura <yomura@hoge.jp>"]
version = "1.4.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
